# Generated by Django 3.2.4 on 2021-12-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_upload_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='pdf'),
        ),
    ]
